version: "3"

services:
    db:
        image: postgres:16
        container_name: robot-suisses-db
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - robot-suisses-db:/var/lib/postgresql/data
    server:
        container_name: robot-suisses-server
        image: registry.gitlab.com/vemate/leadgen/robot-suisse:prod
        environment:
            - DJANGO_SETTINGS_MODULE:robot-suisses.settings.production
        command: gunicorn -w 10 -b unix:/app/server/socket/PROJECT_NAME.sock robot-suisses.wsgi:application
        volumes:
            - ./server/.env:/app/server/.env
            - ./server/static:/app/server/static
            - ./server/media:/app/server/media
            - ./server/socket:/app/server/socket
volumes:
    robot-suisses-db:
