# Generated by Django 5.2.4 on 2025-07-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('message', models.TextField(max_length=500, verbose_name='Message')),
                ('status', models.IntegerField(choices=[(1, 'Unseen'), (2, 'Seen')], default=1, verbose_name='Status')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time')),
            ],
        ),
        migrations.CreateModel(
            name='SocialSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.CharField(blank=True, max_length=260, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=260, null=True, verbose_name='Instagram')),
                ('linkedin', models.CharField(blank=True, max_length=260, null=True, verbose_name='Linkedin')),
                ('whatsapp', models.CharField(blank=True, max_length=260, null=True, verbose_name='WhatsApp')),
                ('x', models.CharField(blank=True, max_length=260, null=True, verbose_name='X')),
                ('youtube', models.CharField(blank=True, max_length=260, null=True, verbose_name='Youtube')),
                ('tiktok', models.CharField(blank=True, max_length=260, null=True, verbose_name='Tiktok')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasicSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60, verbose_name='Company name')),
                ('address1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('t_c', models.URLField(blank=True, max_length=150, null=True, verbose_name='Terms & condition link')),
                ('privacy_policy', models.URLField(blank=True, max_length=150, null=True, verbose_name='Privacy policy link')),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
