# Generated by Django 5.2.4 on 2025-10-23 08:25

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('message', models.TextField(max_length=500, verbose_name='Message')),
                ('status', models.IntegerField(choices=[(1, 'Unseen'), (2, 'Seen')], default=1, verbose_name='Status')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time')),
            ],
        ),
        migrations.CreateModel(
            name='FooterMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=250, verbose_name='Name')),
                ('name_de_ch', models.CharField(max_length=250, verbose_name='Name')),
                ('name_fr_ch', models.CharField(max_length=250, verbose_name='Name')),
                ('name_it_ch', models.CharField(max_length=250, verbose_name='Name')),
                ('link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=250, verbose_name='Name')),
                ('name_de_ch', models.CharField(max_length=250, verbose_name='Name')),
                ('name_fr_ch', models.CharField(max_length=250, verbose_name='Name')),
                ('name_it_ch', models.CharField(max_length=250, verbose_name='Name')),
                ('link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.CharField(blank=True, max_length=260, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=260, null=True, verbose_name='Instagram')),
                ('linkedin', models.CharField(blank=True, max_length=260, null=True, verbose_name='Linkedin')),
                ('whatsapp', models.CharField(blank=True, max_length=260, null=True, verbose_name='WhatsApp')),
                ('x', models.CharField(blank=True, max_length=260, null=True, verbose_name='X')),
                ('youtube', models.CharField(blank=True, max_length=260, null=True, verbose_name='Youtube')),
                ('tiktok', models.CharField(blank=True, max_length=260, null=True, verbose_name='Tiktok')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasicSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_en', models.CharField(max_length=60, verbose_name='Company name')),
                ('company_name_de_ch', models.CharField(max_length=60, verbose_name='Company name')),
                ('company_name_fr_ch', models.CharField(max_length=60, verbose_name='Company name')),
                ('company_name_it_ch', models.CharField(max_length=60, verbose_name='Company name')),
                ('address1_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1')),
                ('address1_de_ch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1')),
                ('address1_fr_ch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1')),
                ('address1_it_ch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1')),
                ('address2_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2')),
                ('address2_de_ch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2')),
                ('address2_fr_ch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2')),
                ('address2_it_ch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('t_c', models.URLField(blank=True, max_length=150, null=True, verbose_name='Terms & condition link')),
                ('privacy_policy', models.URLField(blank=True, max_length=150, null=True, verbose_name='Privacy policy link')),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=250, verbose_name='Name')),
                ('name_de_ch', models.CharField(max_length=250, verbose_name='Name')),
                ('name_fr_ch', models.CharField(max_length=250, verbose_name='Name')),
                ('name_it_ch', models.CharField(max_length=250, verbose_name='Name')),
                ('link', models.CharField(max_length=250, verbose_name='Link')),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='utility.footermenu')),
            ],
        ),
        migrations.CreateModel(
            name='MainMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=250, verbose_name='Name')),
                ('name_de_ch', models.CharField(max_length=250, verbose_name='Name')),
                ('name_fr_ch', models.CharField(max_length=250, verbose_name='Name')),
                ('name_it_ch', models.CharField(max_length=250, verbose_name='Name')),
                ('link', models.CharField(max_length=250, verbose_name='Link')),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='utility.mainmenu')),
            ],
        ),
    ]
