# Generated by Django 5.2.4 on 2025-10-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_alter_basicsetting_address1_de_ch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicsetting',
            name='company_name_de_ch',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Company name de ch'),
        ),
        migrations.AlterField(
            model_name='basicsetting',
            name='company_name_fr_ch',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Company name fr ch'),
        ),
        migrations.AlterField(
            model_name='basicsetting',
            name='company_name_it_ch',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Company name it ch'),
        ),
        migrations.AlterField(
            model_name='footermenu',
            name='name_de_ch',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name de ch'),
        ),
        migrations.AlterField(
            model_name='footermenu',
            name='name_fr_ch',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name fr ch'),
        ),
        migrations.AlterField(
            model_name='footermenu',
            name='name_it_ch',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name it ch'),
        ),
        migrations.AlterField(
            model_name='footermenuitem',
            name='name_de_ch',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name de ch'),
        ),
        migrations.AlterField(
            model_name='footermenuitem',
            name='name_fr_ch',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name fr ch'),
        ),
        migrations.AlterField(
            model_name='footermenuitem',
            name='name_it_ch',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name it ch'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='name_de_ch',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name de ch'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='name_fr_ch',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name fr ch'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='name_it_ch',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name it ch'),
        ),
        migrations.AlterField(
            model_name='mainmenuitem',
            name='name_de_ch',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name de ch'),
        ),
        migrations.AlterField(
            model_name='mainmenuitem',
            name='name_fr_ch',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name fr ch'),
        ),
        migrations.AlterField(
            model_name='mainmenuitem',
            name='name_it_ch',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name it ch'),
        ),
    ]
