# Generated by Django 5.2.4 on 2025-10-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_alter_basicsetting_company_name_de_ch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicsetting',
            name='about_de_ch',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='About de ch'),
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='about_en',
            field=models.TextField(default=3, max_length=500, verbose_name='About en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='about_fr_ch',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='About fr ch'),
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='about_it_ch',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='About it ch'),
        ),
    ]
