# Generated by Django 5.2.4 on 2025-10-08 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_companypage_banner_remove_companypage_logo_and_more'),
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotpage',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robots', to='company.companydetailspage'),
        ),
    ]
