# Generated by Django 5.2.4 on 2025-10-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_remove_robotpage_company_remove_robotpage_og_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotdetailspage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured robots will be displayed on the homepage.'),
        ),
    ]
