FROM python:3.13.5-slim
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE=leadgen.settings.dev
WORKDIR /app/server/
COPY ./server /app/server/
COPY ./server/requirements /app/server/
RUN pip install --upgrade pip
RUN pip install -r requirements/dev.txt
