FROM python:3.13.5
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=robot-suisses.settings.production
WORKDIR /app/server/
COPY ./server /app/server/
COPY ./server/requirements /app/server/
RUN pip install --upgrade pip
RUN pip install -r requirements/prod.txt

CMD ["gunicorn", "robot-suisses.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]