# Generated by Django 5.2.4 on 2025-11-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('source_page', models.IntegerField(default=0)),
                ('is_detail_fetched', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField()),
                ('banner_image', models.URLField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('detail_country', models.CharField(blank=True, max_length=255, null=True)),
                ('detail_type', models.CharField(blank=True, max_length=100, null=True)),
                ('detail_employees', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_persons', models.ManyToManyField(blank=True, related_name='organizations', to='companies.contactperson')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
