# Generated by Django 5.2.4 on 2025-10-28 10:29

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([], blank=True, block_lookup={}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_keywords',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Og keywords'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='robots_directive',
            field=models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow'), ('noindex, nofollow', 'No Index, No Follow')], default='index, follow', help_text='Meta robots tag for SEO', max_length=20),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_keywords', models.CharField(blank=True, max_length=550, null=True, verbose_name='Og keywords')),
                ('robots_directive', models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow'), ('noindex, nofollow', 'No Index, No Follow')], default='index, follow', help_text='Meta robots tag for SEO', max_length=20)),
                ('title_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title en')),
                ('title_dech', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title dech')),
                ('title_frch', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title frch')),
                ('title_itch', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title itch')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_keywords', models.CharField(blank=True, max_length=550, null=True, verbose_name='Og keywords')),
                ('robots_directive', models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow'), ('noindex, nofollow', 'No Index, No Follow')], default='index, follow', help_text='Meta robots tag for SEO', max_length=20)),
                ('title_en', models.CharField(blank=True, max_length=250, null=True)),
                ('title_dech', models.CharField(blank=True, max_length=250, null=True)),
                ('title_frch', models.CharField(blank=True, max_length=250, null=True)),
                ('title_itch', models.CharField(blank=True, max_length=250, null=True)),
                ('body', wagtail.fields.StreamField([], blank=True, block_lookup={}, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('tags_en', models.CharField(blank=True, max_length=250, null=True)),
                ('tags_dech', models.CharField(blank=True, max_length=250, null=True)),
                ('tags_frch', models.CharField(blank=True, max_length=250, null=True)),
                ('tags_itch', models.CharField(blank=True, max_length=250, null=True)),
                ('short_description_en', models.TextField(blank=True, null=True)),
                ('short_description_dech', models.TextField(blank=True, null=True)),
                ('short_description_frch', models.TextField(blank=True, null=True)),
                ('short_description_itch', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.author')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_keywords', models.CharField(blank=True, max_length=550, null=True, verbose_name='Og keywords')),
                ('robots_directive', models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow'), ('noindex, nofollow', 'No Index, No Follow')], default='index, follow', help_text='Meta robots tag for SEO', max_length=20)),
                ('tag_en', models.CharField(help_text='The tag for the page.', max_length=255)),
                ('tag_dech', models.CharField(blank=True, help_text='German tag', max_length=255, null=True)),
                ('tag_frch', models.CharField(blank=True, help_text='French tag', max_length=255, null=True)),
                ('tag_itch', models.CharField(blank=True, help_text='Italian tag', max_length=255, null=True)),
                ('hero_title_en', models.CharField(max_length=255)),
                ('hero_title_dech', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_title_frch', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_title_itch', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_description_en', models.TextField(blank=True)),
                ('hero_description_dech', models.TextField(blank=True, null=True)),
                ('hero_description_frch', models.TextField(blank=True, null=True)),
                ('hero_description_itch', models.TextField(blank=True, null=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
