# Generated by Django 5.2.4 on 2025-10-10 11:11

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_og_image_homepage_og_keywords_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_keywords', models.CharField(blank=True, max_length=550, null=True, verbose_name='Og keywords')),
                ('robots_directive', models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow'), ('noindex, nofollow', 'No Index, No Follow')], default='index, follow', help_text='Meta robots tag for SEO', max_length=20)),
                ('title_ar', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title ar')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_keywords', models.CharField(blank=True, max_length=550, null=True, verbose_name='Og keywords')),
                ('robots_directive', models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow'), ('noindex, nofollow', 'No Index, No Follow')], default='index, follow', help_text='Meta robots tag for SEO', max_length=20)),
                ('title_ar', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title ar')),
                ('body', wagtail.fields.StreamField([], blank=True, block_lookup={}, null=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured blog')),
                ('tags', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tags: Comma separated')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('short_description_ar', models.TextField(blank=True, null=True, verbose_name='Short description ar')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.author', verbose_name='Author')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_keywords', models.CharField(blank=True, max_length=550, null=True, verbose_name='Og keywords')),
                ('robots_directive', models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow'), ('noindex, nofollow', 'No Index, No Follow')], default='index, follow', help_text='Meta robots tag for SEO', max_length=20)),
                ('title_ar', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title ar')),
                ('hero_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Hero title')),
                ('hero_title_ar', models.CharField(blank=True, max_length=250, null=True, verbose_name='Hero title ar')),
                ('hero_subtitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='Hero subtitle')),
                ('hero_subtitle_ar', models.CharField(blank=True, max_length=250, null=True, verbose_name='Hero subtitle ar')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
