# Generated by Django 5.2.4 on 2025-10-28 10:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='body',
            field=wagtail.fields.StreamField([('title', 12), ('banner_image', 14), ('banner_video', 16), ('carousel', 19), ('richtext', 22), ('faq', 25), ('media_text', 31)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': ' (EN)', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': ' (DE)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': ' (FR)', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': ' (IT)', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('en', 1), ('dech', 2), ('frch', 3), ('itch', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {'help_text': ' (EN)', 'required': True}), 7: ('wagtail.blocks.RichTextBlock', (), {'help_text': ' (DE)', 'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {'help_text': ' (FR)', 'required': False}), 9: ('wagtail.blocks.RichTextBlock', (), {'help_text': ' (IT)', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('en', 6), ('dech', 7), ('frch', 8), ('itch', 9)]], {}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')]}), 12: ('wagtail.blocks.StructBlock', [[('bg_color_code', 0), ('tag', 5), ('title', 10), ('alignment', 11)]], {}), 13: ('home.blocks.ImageChooserBlock', (), {'required': False}), 14: ('wagtail.blocks.StructBlock', [[('image', 13)]], {}), 15: ('wagtail.blocks.URLBlock', (), {'required': True}), 16: ('wagtail.blocks.StructBlock', [[('video_url', 15)]], {}), 17: ('home.blocks.ImageChooserBlock', (), {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('images', 18)]], {}), 20: ('wagtail.blocks.RichTextBlock', (), {'help_text': ' (EN)', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('en', 20), ('dech', 7), ('frch', 8), ('itch', 9)]], {}), 22: ('wagtail.blocks.StructBlock', [[('content', 21)]], {}), 23: ('wagtail.blocks.StructBlock', [[('question', 5), ('answer', 10)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {}), 25: ('wagtail.blocks.StructBlock', [[('items', 24)]], {}), 26: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left_media', 'Left media / Right text'), ('right_media', 'Left text / Right media')]}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image', 'Image'), ('video', 'YouTube (URL)')]}), 28: ('wagtail.blocks.URLBlock', (), {'required': False}), 29: ('wagtail.blocks.CharBlock', (), {'help_text': ' (EN)', 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('en', 29), ('dech', 2), ('frch', 3), ('itch', 4)]], {}), 31: ('wagtail.blocks.StructBlock', [[('layout', 26), ('description', 10), ('media_type', 27), ('image', 13), ('video_url', 28), ('button_text', 30), ('button_link', 0)]], {})}, null=True),
        ),
    ]
