# Generated by Django 5.2.4 on 2025-10-06 10:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_servicelistpage'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelistpage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='servicelistpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='termspage',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='termspage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='termspage',
            name='page_ptr',
        ),
        migrations.CreateModel(
            name='PublicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_keywords', models.CharField(blank=True, max_length=550, null=True, verbose_name='Og keywords')),
                ('robots_directive', models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow'), ('noindex, nofollow', 'No Index, No Follow')], default='index, follow', help_text='Meta robots tag for SEO', max_length=20)),
                ('body', wagtail.fields.StreamField([('banner_block', 1), ('richtext_block', 2), ('two_image_block', 3), ('faq_block', 8)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('image', 0)]], {}), 2: ('home.blocks.RichtextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('image1', 0), ('image2', 0)]], {}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.RichTextBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('question', 4), ('answer', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('items', 7)]], {})}, null=True)),
                ('cover_image', models.ForeignKey(blank=True, help_text='Cover image for the service detail page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Cover Image')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='PrivacyPage',
        ),
        migrations.DeleteModel(
            name='ServiceListPage',
        ),
        migrations.DeleteModel(
            name='TermsPage',
        ),
    ]
