# Generated by Django 5.2.4 on 2025-10-28 12:49

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_publicpage_body'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_keywords', models.CharField(blank=True, max_length=550, null=True, verbose_name='Og keywords')),
                ('robots_directive', models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow'), ('noindex, nofollow', 'No Index, No Follow')], default='index, follow', help_text='Meta robots tag for SEO', max_length=20)),
                ('body', wagtail.fields.StreamField([('page_header', 16), ('title', 20), ('cards', 21), ('stats', 24), ('team', 29), ('quote', 30), ('cta', 31), ('banner_video', 33), ('spacer', 35)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': ' (EN)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': ' (DE)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': ' (FR)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': ' (IT)', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('en', 0), ('dech', 1), ('frch', 2), ('itch', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': ' (EN)', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('en', 5), ('dech', 1), ('frch', 2), ('itch', 3)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'help_text': ' (EN)', 'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {'help_text': ' (DE)', 'required': False}), 9: ('wagtail.blocks.RichTextBlock', (), {'help_text': ' (FR)', 'required': False}), 10: ('wagtail.blocks.RichTextBlock', (), {'help_text': ' (IT)', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('en', 7), ('dech', 8), ('frch', 9), ('itch', 10)]], {}), 12: ('home.blocks.ImageChooserBlock', (), {}), 13: ('wagtail.blocks.CharBlock', (), {'required': False}), 14: ('wagtail.blocks.StructBlock', [[('text', 4), ('link', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('tag', 4), ('hero_title', 6), ('hero_subtitle', 11), ('image', 12), ('buttons', 15)]], {}), 17: ('wagtail.blocks.RichTextBlock', (), {'help_text': ' (EN)', 'required': True}), 18: ('wagtail.blocks.StructBlock', [[('en', 17), ('dech', 8), ('frch', 9), ('itch', 10)]], {}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')]}), 20: ('wagtail.blocks.StructBlock', [[('bg_color_code', 13), ('tag', 6), ('title', 18), ('alignment', 19)]], {}), 21: ('wagtail.blocks.StructBlock', [[('icon', 13), ('description', 18)]], {}), 22: ('wagtail.blocks.StructBlock', [[('description', 18)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {}), 24: ('wagtail.blocks.StructBlock', [[('items', 23)]], {}), 25: ('home.blocks.ImageChooserBlock', (), {'required': False}), 26: ('wagtail.blocks.StructBlock', [[('image', 25), ('description', 11)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {}), 28: ('wagtail.blocks.StructBlock', [[('categories', 27)]], {}), 29: ('wagtail.blocks.StructBlock', [[('team', 28)]], {}), 30: ('wagtail.blocks.StructBlock', [[('quote', 11), ('author', 4)]], {}), 31: ('wagtail.blocks.StructBlock', [[('image', 25), ('subtitle', 11), ('button_text', 4), ('button_link', 13)]], {}), 32: ('wagtail.blocks.URLBlock', (), {'required': True}), 33: ('wagtail.blocks.StructBlock', [[('video_url', 32)]], {}), 34: ('wagtail.blocks.IntegerBlock', (), {'default': 20, 'help_text': 'Height in rem'}), 35: ('wagtail.blocks.StructBlock', [[('height', 34)]], {})}, null=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
