# Generated by Django 5.2.4 on 2025-10-28 13:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_aboutpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.StreamField([('page_header', 16), ('title', 20), ('cards', 23), ('stats', 26), ('team', 31), ('quote', 32), ('cta', 33), ('banner_video', 35), ('spacer', 37)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': ' (EN)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': ' (DE)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': ' (FR)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': ' (IT)', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('en', 0), ('dech', 1), ('frch', 2), ('itch', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': ' (EN)', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('en', 5), ('dech', 1), ('frch', 2), ('itch', 3)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'help_text': ' (EN)', 'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {'help_text': ' (DE)', 'required': False}), 9: ('wagtail.blocks.RichTextBlock', (), {'help_text': ' (FR)', 'required': False}), 10: ('wagtail.blocks.RichTextBlock', (), {'help_text': ' (IT)', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('en', 7), ('dech', 8), ('frch', 9), ('itch', 10)]], {}), 12: ('home.blocks.ImageChooserBlock', (), {}), 13: ('wagtail.blocks.CharBlock', (), {'required': False}), 14: ('wagtail.blocks.StructBlock', [[('text', 4), ('link', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('tag', 4), ('hero_title', 6), ('hero_subtitle', 11), ('image', 12), ('buttons', 15)]], {}), 17: ('wagtail.blocks.RichTextBlock', (), {'help_text': ' (EN)', 'required': True}), 18: ('wagtail.blocks.StructBlock', [[('en', 17), ('dech', 8), ('frch', 9), ('itch', 10)]], {}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')]}), 20: ('wagtail.blocks.StructBlock', [[('bg_color_code', 13), ('tag', 6), ('title', 18), ('alignment', 19)]], {}), 21: ('wagtail.blocks.StructBlock', [[('icon', 13), ('description', 18)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {}), 23: ('wagtail.blocks.StructBlock', [[('cards', 22)]], {}), 24: ('wagtail.blocks.StructBlock', [[('description', 18)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {}), 26: ('wagtail.blocks.StructBlock', [[('items', 25)]], {}), 27: ('home.blocks.ImageChooserBlock', (), {'required': False}), 28: ('wagtail.blocks.StructBlock', [[('image', 27), ('description', 11)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {}), 30: ('wagtail.blocks.StructBlock', [[('categories', 29)]], {}), 31: ('wagtail.blocks.StructBlock', [[('team', 30)]], {}), 32: ('wagtail.blocks.StructBlock', [[('quote', 11), ('author', 4)]], {}), 33: ('wagtail.blocks.StructBlock', [[('image', 27), ('subtitle', 11), ('button_text', 4), ('button_link', 13)]], {}), 34: ('wagtail.blocks.URLBlock', (), {'required': True}), 35: ('wagtail.blocks.StructBlock', [[('video_url', 34)]], {}), 36: ('wagtail.blocks.IntegerBlock', (), {'default': 20, 'help_text': 'Height in rem'}), 37: ('wagtail.blocks.StructBlock', [[('height', 36)]], {})}, null=True),
        ),
    ]
