# Generated by Django 5.2.4 on 2025-10-07 05:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_servicepage_og_image_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robotpage',
            options={'verbose_name': 'Robot Page', 'verbose_name_plural': 'Robot Pages'},
        ),
        migrations.RemoveField(
            model_name='robotpage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='robotpage',
            name='og_keywords',
        ),
        migrations.RemoveField(
            model_name='robotpage',
            name='robots_directive',
        ),
        migrations.AddField(
            model_name='robotpage',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='robotpage',
            name='button_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='robotpage',
            name='button_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='robotpage',
            name='subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
