# Generated by Django 5.2.4 on 2025-10-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_robotpage_options_remove_robotpage_og_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotpage',
            name='hero_title',
            field=models.CharField(default=4, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='robotpage',
            name='button_link',
            field=models.CharField(blank=True),
        ),
    ]
