# Generated by Django 5.2.4 on 2025-10-07 05:45

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_robotpage_hero_title_alter_robotpage_button_link'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicpage',
            name='body',
            field=wagtail.fields.StreamField([('banner_block', 3), ('richtext_block', 4), ('two_image_block', 6), ('faq_block', 11)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image', 'Image'), ('video', 'Video')], 'help_text': 'Select whether this banner is an image or a video'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload an image for the banner', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enter a video URL for the banner', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('media_type', 0), ('image', 1), ('video_url', 2)]], {}), 4: ('home.blocks.RichtextBlock', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('image1', 5), ('image2', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.RichTextBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('question', 7), ('answer', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('items', 10)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='robotdetailpage',
            name='body',
            field=wagtail.fields.StreamField([('banner_block', 3), ('richtext_block', 4), ('two_image_block', 6), ('faq_block', 11)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image', 'Image'), ('video', 'Video')], 'help_text': 'Select whether this banner is an image or a video'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload an image for the banner', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enter a video URL for the banner', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('media_type', 0), ('image', 1), ('video_url', 2)]], {}), 4: ('home.blocks.RichtextBlock', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('image1', 5), ('image2', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.RichTextBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('question', 7), ('answer', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('items', 10)]], {})}, null=True),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_keywords', models.CharField(blank=True, max_length=550, null=True, verbose_name='Og keywords')),
                ('robots_directive', models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow'), ('noindex, nofollow', 'No Index, No Follow')], default='index, follow', help_text='Meta robots tag for SEO', max_length=20)),
                ('title_ar', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title ar')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_keywords', models.CharField(blank=True, max_length=550, null=True, verbose_name='Og keywords')),
                ('robots_directive', models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow'), ('noindex, nofollow', 'No Index, No Follow')], default='index, follow', help_text='Meta robots tag for SEO', max_length=20)),
                ('title_ar', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title ar')),
                ('body', wagtail.fields.StreamField([('title', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main title for the banner', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional subtitle or tagline', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1)]], {})}, null=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured blog')),
                ('tags', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tags: Comma separated')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('short_description_ar', models.TextField(blank=True, null=True, verbose_name='Short description ar')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.author', verbose_name='Author')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_keywords', models.CharField(blank=True, max_length=550, null=True, verbose_name='Og keywords')),
                ('robots_directive', models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow'), ('noindex, nofollow', 'No Index, No Follow')], default='index, follow', help_text='Meta robots tag for SEO', max_length=20)),
                ('title_ar', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title ar')),
                ('hero_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Hero title')),
                ('hero_title_ar', models.CharField(blank=True, max_length=250, null=True, verbose_name='Hero title ar')),
                ('hero_subtitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='Hero subtitle')),
                ('hero_subtitle_ar', models.CharField(blank=True, max_length=250, null=True, verbose_name='Hero subtitle ar')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='RegistrationPage',
        ),
    ]
