# Generated by Django 5.2.4 on 2025-10-10 12:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_blogdetailpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotdetailspage',
            name='body',
            field=wagtail.fields.StreamField([('title', 4), ('banner_image', 6), ('banner_video', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main title for the banner', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main title for the banner', 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional subtitle or tagline', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')], 'help_text': 'Choose the text alignment'}), 4: ('wagtail.blocks.StructBlock', [[('title_en', 0), ('title_de_ch', 1), ('title_fr_ch', 1), ('title_it_ch', 1), ('subtitle_en', 2), ('subtitle_de_ch', 2), ('subtitle_fr_ch', 2), ('subtitle_it_ch', 2), ('alignment', 3)]], {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload an image for the banner', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 5)]], {}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enter a video URL for the banner', 'required': True}), 8: ('wagtail.blocks.StructBlock', [[('video_url', 7)]], {})}, null=True),
        ),
    ]
