# Generated by Django 5.2.4 on 2025-10-07 09:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_publicpage_body_alter_robotdetailpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='body',
            field=wagtail.fields.StreamField([('title', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main title for the banner', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional subtitle or tagline', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')], 'help_text': 'Choose the text alignment'}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('alignment', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='publicpage',
            name='body',
            field=wagtail.fields.StreamField([('banner_block', 3), ('richtext_block', 4), ('two_image_block', 12), ('faq_block', 17)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image', 'Image'), ('video', 'Video')], 'help_text': 'Select whether this banner is an image or a video'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload an image for the banner', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enter a video URL for the banner', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('media_type', 0), ('image', 1), ('video_url', 2)]], {}), 4: ('home.blocks.RichtextBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title for the first image', 'required': False}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Subtitle for the first image', 'required': False}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'First image', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title for the second image', 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'Subtitle for the second image', 'required': False}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Second image', 'required': True}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('top', 'Image Top'), ('bottom', 'Image Bottom')], 'help_text': 'Position of the image section'}), 12: ('wagtail.blocks.StructBlock', [[('title1', 5), ('subtitle1', 6), ('image1', 7), ('title2', 8), ('subtitle2', 9), ('image2', 10), ('position', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {}), 14: ('wagtail.blocks.RichTextBlock', (), {}), 15: ('wagtail.blocks.StructBlock', [[('question', 13), ('answer', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('items', 16)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='robotdetailpage',
            name='body',
            field=wagtail.fields.StreamField([('banner_block', 3), ('richtext_block', 4), ('two_image_block', 12), ('faq_block', 17)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image', 'Image'), ('video', 'Video')], 'help_text': 'Select whether this banner is an image or a video'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload an image for the banner', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enter a video URL for the banner', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('media_type', 0), ('image', 1), ('video_url', 2)]], {}), 4: ('home.blocks.RichtextBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title for the first image', 'required': False}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Subtitle for the first image', 'required': False}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'First image', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title for the second image', 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'Subtitle for the second image', 'required': False}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Second image', 'required': True}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('top', 'Image Top'), ('bottom', 'Image Bottom')], 'help_text': 'Position of the image section'}), 12: ('wagtail.blocks.StructBlock', [[('title1', 5), ('subtitle1', 6), ('image1', 7), ('title2', 8), ('subtitle2', 9), ('image2', 10), ('position', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {}), 14: ('wagtail.blocks.RichTextBlock', (), {}), 15: ('wagtail.blocks.StructBlock', [[('question', 13), ('answer', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('items', 16)]], {})}, null=True),
        ),
    ]
