# Generated by Django 5.2.4 on 2025-10-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_blogdetailpage_body_alter_publicpage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robotdetailpage',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='robotdetailpage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='robotdetailpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='robotpage',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='robotpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='AboutUsPage',
        ),
        migrations.DeleteModel(
            name='RobotDetailPage',
        ),
        migrations.DeleteModel(
            name='RobotPage',
        ),
    ]
