# Generated by Django 5.2.4 on 2025-10-08 07:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_robotdetailpage_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='body',
            field=wagtail.fields.StreamField([('title', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main title for the banner', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Main title for the banner', 'null': True, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional subtitle or tagline', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'blank': True, 'help_text': 'Optional subtitle or tagline', 'null': True, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')], 'help_text': 'Choose the text alignment'}), 5: ('wagtail.blocks.StructBlock', [[('title_en', 0), ('title_de_ch', 1), ('title_fr_ch', 1), ('title_it_ch', 1), ('subtitle_en', 2), ('subtitle_de_ch', 3), ('subtitle_fr_ch', 3), ('subtitle_it_ch', 3), ('alignment', 4)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='publicpage',
            name='body',
            field=wagtail.fields.StreamField([], blank=True, block_lookup={}, null=True),
        ),
    ]
