# Generated by Django 5.2.4 on 2025-10-08 07:09

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypage',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='companypage',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='companypage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='companypage',
            name='page_ptr',
        ),
        migrations.CreateModel(
            name='CompanyCategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_keywords', models.CharField(blank=True, max_length=550, null=True, verbose_name='Og keywords')),
                ('robots_directive', models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow'), ('noindex, nofollow', 'No Index, No Follow')], default='index, follow', help_text='Meta robots tag for SEO', max_length=20)),
                ('title_ar', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title ar')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CompanyDetailsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_keywords', models.CharField(blank=True, max_length=550, null=True, verbose_name='Og keywords')),
                ('robots_directive', models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow'), ('noindex, nofollow', 'No Index, No Follow')], default='index, follow', help_text='Meta robots tag for SEO', max_length=20)),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_de_ch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (German - Switzerland)')),
                ('name_fr_ch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (French - Switzerland)')),
                ('name_it_ch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (Italian - Switzerland)')),
                ('company_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('integrator', 'Integrator'), ('distributor', 'Distributor'), ('supplier', 'Supplier'), ('service_provider', 'Service Provider'), ('other', 'Other')], max_length=50, verbose_name='Company Type')),
                ('description_en', wagtail.fields.RichTextField(blank=True, verbose_name='Description (English)')),
                ('description_de_ch', wagtail.fields.RichTextField(blank=True, verbose_name='Description (German - Switzerland)')),
                ('description_fr_ch', wagtail.fields.RichTextField(blank=True, verbose_name='Description (French - Switzerland)')),
                ('description_it_ch', wagtail.fields.RichTextField(blank=True, verbose_name='Description (Italian - Switzerland)')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('industries', models.JSONField(blank=True, null=True, verbose_name='Industries')),
                ('certifications', models.JSONField(blank=True, null=True, verbose_name='Certifications')),
                ('locations', models.JSONField(blank=True, null=True, verbose_name='Branch Locations')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20, verbose_name='Status')),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='companysociallink',
            name='company',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='company.companydetailspage'),
        ),
        migrations.CreateModel(
            name='CompanyIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_keywords', models.CharField(blank=True, max_length=550, null=True, verbose_name='Og keywords')),
                ('robots_directive', models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow'), ('noindex, nofollow', 'No Index, No Follow')], default='index, follow', help_text='Meta robots tag for SEO', max_length=20)),
                ('title_ar', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title ar')),
                ('hero_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Hero title')),
                ('hero_title_ar', models.CharField(blank=True, max_length=250, null=True, verbose_name='Hero title ar')),
                ('hero_subtitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='Hero subtitle')),
                ('hero_subtitle_ar', models.CharField(blank=True, max_length=250, null=True, verbose_name='Hero subtitle ar')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='CompanyCategory',
        ),
    ]
