# Generated by Django 5.2.4 on 2025-10-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_companypage_banner_remove_companypage_logo_and_more'),
        ('robot', '0002_alter_robotpage_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyPage',
        ),
    ]
