# Generated by Django 5.2.4 on 2025-11-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='company',
            field=models.CharField(default=9, max_length=255),
            preserve_default=False,
        ),
    ]
